### ISSUE TITLE
OC全部覆盖还是提示0.6.5

### ISSUE THREAD

**Issue by Kevin-Ben** [Jiangmenghao/NUC8i5BEH#16]
把现有的OC删除了，再使用master分支的OC放到本机后重启，打开`hackintool` 提示还是旧版本，请问如何解决？

**Comment by coolicer** [comment]
我那天也是折腾好久，最后不知道怎么就更新上去。好像有点清缓存什么的

**Comment by coolicer** [comment]
帮你找了一下，真的要清

> Q：opencore升级版本后，Hackintool上的引导依旧显示原来的版本号。  

1. 使用opencore configure工具打开EFI引导分区OC目录下config.plist文件
2. Misc—Security—AllowNvramReset选项勾选上，
3. 然后保存重启，进入菜单栏页面选择rest nvram选项，
4. 系统会自动重启，重启后在去Hackintool上看引导的OC版本号，已经显示为最新版本。

**Comment by Kevin-Ben** [comment]
> 帮你找了一下，真的要清
> 
> > Q：opencore升级版本后，Hackintool上的引导依旧显示原来的版本号。
> 
> 1. 使用opencore configure工具打开EFI引导分区OC目录下config.plist文件
> 2. Misc—Security—AllowNvramReset选项勾选上，
> 3. 然后保存重启，进入菜单栏页面选择rest nvram选项，
> 4. 系统会自动重启，重启后在去Hackintool上看引导的OC版本号，已经显示为最新版本。

按照这个操作了，还是显示老版本

**Comment by coolicer** [comment]
@Kevin-Ben 我还专门试了一次，是可以的。

**Comment by Kevin-Ben** [comment]
> 

OC 引导界面没有rest nvram选项

**Comment by Kevin-Ben** [comment]
> @Kevin-Ben 我还专门试了一次，是可以的。

3.然后保存重启，进入菜单栏页面选择rest nvram选项，这步没有操作，本源未添加OC rest nvram 选项，需要自己在OCC上配置。

**Comment by coolicer** [comment]
@Kevin-Ben reset这个在工具上。hackintool某个选项卡
