### ISSUE TITLE
请问，从13.6升级到14之后蓝牙可用，wifi不可用是什么问题啊？

### ISSUE THREAD

**Issue by billie-zhou** [Jiangmenghao/NUC8i5BEH#26]
使用的免驱网卡bcm94360cs2，配置使用的项目里最新那个，升级后wifi开关无法打开，看了下蓝牙倒是可以使用。

**Comment by Jiangmenghao** [comment]
请查看 [sonoma-only](https://github.com/Jiangmenghao/NUC8i5BEH/tree/sonoma-only) 分支

**Comment by billie-zhou** [comment]
谢谢，已解决

**Comment by tong3jie** [comment]
原版 intel网卡，我在13.6的时候，WIFI就不可用了
